language: cpp

cache: ccache

env:
  - CHARM_VERSION=charm-6.9.0

matrix:
  include:
    - os: linux
      name: "ChaNGa with NetLRTS-Linux SMP Charm++"
      dist: xenial
      script:
        - git clone git://github.com/N-BodyShop/utility.git
        - echo $TRAVIS_BUILD_DIR
        - export STRUCT_DIR=$TRAVIS_BUILD_DIR/utility/structures
        - echo $STRUCT_DIR
