language: cpp

cache: ccache

env:
  - CHARM_VERSION=charm-6.9.0

matrix:
  include:
    - os: linux
      name: "ChaNGa with NetLRTS-Linux SMP Charm++"
      dist: xenial
      script:
        - git clone git://github.com/N-BodyShop/utility.git
        - export STRUCT_DIR=$TRAVIS_BUILD_DIR/utility/structures
        - wget http://charm.cs.illinois.edu/distrib/$CHARM_VERSION.tar.gz
        - tar -xzf $CHARM_VERSION.tar.gz
        - cd $CHARM_VERSION
        - ./build ChaNGa netlrts-linux-x86_64 smp --with-production --enable-error-checking -j4
        - cd ..
        - export CHARM_DIR=$TRAVIS_BUILD_DIR/$CHARM_VERSION
        - ./configure
        - make clean; make -j4
        - cd teststep
        - make clean; make
        - cd ..
        - make dist-clean
