/// @file lymanwerner.h
/// Declarations for Lyman Werner calculation.

/* inline function used in feedback.C and starform.C to calculate the Lyman Werner luminosity for a star particle of a given age and mass*/
inline double calcLogSSPLymanWerner(double dAgelog, double dMassLog)
{
 /* Variables below are to a polynomial fit for data representing a SSP generated by Starburst99*/    
    double a0 = -84550.812,
      a1 =  54346.066,
      a2 = -13934.144,
      a3 =  1782.1741,
      a4 = -113.68717,
      a5 =  2.8930795;
    return a0
      + a1*dAgelog
      + a2*dAgelog*dAgelog
      + a3*dAgelog*dAgelog*dAgelog
      + a4*dAgelog*dAgelog*dAgelog*dAgelog
      + a5*dAgelog*dAgelog*dAgelog*dAgelog*dAgelog + dMassLog;
}
