m = column('imf.out', 0)
ms = column('imf.out', 1)
mscn = column('imf.out', 2)
mscm = column('imf.out', 3)
kr = column('imf.out', 4)
krcn = column('imf.out', 5)
krcm = column('imf.out', 6)
kr01 = column('imf.out', 7)
kr01cn = column('imf.out', 8)
kr01cm = column('imf.out', 9)
ch = column('imf.out', 10)
chcn = column('imf.out', 11)
chcm = column('imf.out', 12)
pylab.semilogx(m, ms/mscn[0], m, kr/krcn[0], m, kr01/kr01cn[0], m, ch/chcn[0])
pylab.semilogx(m, m*ms/mscm[0], m, m*kr/krcm[0], m, m*kr01/krcm[0], m, m*ch/chcm[0])
