# CXXFLAGS = -O3 -I../structures -I../ParallelGravity -I. -DINTERLIST_VER=2
# CHARMC = $(HOME)/work/charm-ci/charm/bin/charmc $(OPTS)
# CXX = $(CHARMC)
# CC = $(CXX)

# TARGETS = GenericTreeNode.o

# .PHONY: all clean

# all: $(TARGETS)

# clean:
# 	rm -f $(TARGETS)
