from pylab import *
from user import *

r = column('gas.prof', 0)
rho = column('gas.prof', 12)
pres = column('gas.prof', 14)
vr = column('gas.prof', 5)
rc = column('cha.prof', 0)
rhoc = column('cha.prof', 12)
presc = column('cha.prof', 14)
vrc = column('cha.prof', 5)
s = pres/rho**(5./3.)
sc = presc/rhoc**(5./3.)

loglog(r, rho)
subplot(221)
loglog(r, rho)
loglog(rc, rhoc)
ylabel('density')
subplot(222)
loglog(r, pres)
loglog(rc, presc)
ylabel('Pressure')
subplot(223)
loglog(r, s)
loglog(rc, sc)
ylabel('Entropy')
subplot(224)
semilogx(r, vr)
semilogx(rc, vrc)
ylabel ('velocity')
