name: ChaNGa-SMP

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build-charm++
      run: |
        export CHARM_VERSION=7.0.0
        git clone https://github.com/charmplusplus/charm.git
        cd charm
        git checkout v$CHARM_VERSION
        ./build ChaNGa netlrts-linux-x86_64 smp --with-production --enable-error-checking -j4
        cd ..
    - name: build-changa
      run: |
        git clone https://github.com/N-bodyshop/utility
        export STRUCT_DIR=$PWD/utility/structures
        export CHARM_DIR=$PWD/charm
        ./configure
        make -j4
    - name: test-changa
      run: |
        cd teststep
        make test
